export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const USER_LOADING = 'USER_LOADING';
export const SET_USER = 'SET_USER';
